Blog/urls.py
from django.urls import path
from .views import (BlogIndexView, Login, LogOut, ReplyHandler, Registration,
                    UpdateDeleteComment, VotesHandler)

app_name = 'Blog'

urlpatterns = [
    path('',
        BlogIndexView.as_view(),
        name='Blog_index',
        ),
    path(
        'Comment/Delete/<int:comment_pk>/',
        UpdateDeleteComment,
        name='Delete_comment',
        ),
    path(
        'Comment/Update/<int:comment_pk>/',
        UpdateDeleteComment,
        name='Update_comment',
        ),
    path(
        'Login/',
        Login.as_view(),
        name='Login',
        ),
    path(
        'Login/<str:error>/',
        BlogIndexView.as_view(),
        name="Login_error",
        ),
    path(
        'Logout/',
        LogOut.as_view(),
        name='Logout',
        ),
    path(
        'Reply/<str:parent_comment_pk>/',
        ReplyHandler,
        name='Reply',
        ),
    path(
        'Registration/',
        Registration,
        name='Registration',
        ),
    path(
        'Registration/<str:error_type>/',
         BlogIndexView.as_view(),
         name='Registration_error',
        ),
    path(
        'Vote/<int:comment_pk>/<str:vote_type>/',
        VotesHandler,
        name='Vote',
        ),
]

CallofCthoder/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(
        'admin/',
        admin.site.urls,
        ),
    path(
        'blog/',
        include('Blog.urls'),
        ),
    path('',
        include('Profile.urls'),
        ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Profile/urls.py
from django.urls import path

from .views import IndexView, SubscriptionHandler, ResumeView

app_name = 'Profile'

urlpatterns = [
    path(
        '',
        IndexView.as_view(),
        name='index',
        ),
    path(
        'BNResume/',
        ResumeView,
        name='resume',
        ),
    path(
        'Subscription/',
        SubscriptionHandler,
        name='subscription',
        ),
]

Profile/models.py
from django.db import models

class Introduction(models.Model):
    intro = models.TextField(max_length=275, blank=True)
    upload_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-upload_date']
        get_latest_by = 'upload_date'

class AboutMe(models.Model):
    description = models.TextField(max_length=756, blank=True)
    profile_picture = models.ImageField(
        upload_to='Profile/AboutMe/',
        blank=True,
        null=True,
        )
    post_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.post_date}'

    class Meta:
        ordering = ['-post_date']
        get_latest_by = 'post_date'

class Projects(models.Model):
    title = models.CharField(max_length=45, blank=True)
    summary = models.TextField(max_length=219, blank=True)
    project_picture = models.ImageField(
        upload_to='Profile/Projects/',
        blank=True,
        null=True,
        )
    project_url = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.title

class Resume(models.Model):
    resume_pdf = models.FileField(
        upload_to='Profile/Resume/',
        blank=True,
        null=True,
        )

    def __str__(self):
        return 'Resume'

    class Meta():
        ordering = ['-pk']

class ContactInformation(models.Model):
    email = models.EmailField(blank=True, null=True)
    github = models.URLField(blank=True, null=True)
    linkedin = models.URLField(blank=True, null=True)

    def __str__(self):
        return 'Contact Info'

class Subscription(models.Model):
    user_email = models.EmailField(blank=False, null=True, unique=True)

    def __str__(self):
        return self.user_email

Profile/views.py
from django.http import JsonResponse
from django.shortcuts import render, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import TemplateView
from CallofCthoder.settings import STATIC_DIR
from Blog.models import BlogPost
from .models import (AboutMe, ContactInformation, Introduction, Subscription,
                    Projects, Resume)

class IndexView(TemplateView):
    template_name = 'Profile/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Generates context for the blurb
        if Introduction.objects.first() is not None:
            blurb = Introduction.objects.latest()
        else:
            blurb = 'Placeholder'

        context['blurb'] = blurb.intro

        # Generates context for the about me section
        if AboutMe.objects.first() is not None:
            about_me = AboutMe.objects.first()
        else:
            about_me = AboutMe.objects.none()

        context['about_me'] = about_me

        # Generates context for the project section
        context['projects'] = Projects.objects.all()

        # Generate the context for the most recent blogpost preview
        context['recent_blogpost'] = BlogPost.objects.first()

        return context

def ResumeView(request):
    """
    View for displaying Resume.
    """
    try:
        resume = Resume.objects.all().first()
        response = HttpResponse(resume.resume_pdf.read(), content_type='application/pdf')
        response['Content-Disposition'] = 'inline; filename="foo.pdf"'
    except:
        response = HttpResponse('Error')
    return response

def SubscriptionHandler(request):

    if request.method == 'POST' and request.is_ajax():
        user_email = request.POST['user_email']
        Subscription.objects.create(user_email=user_email)

    return JsonResponse({'success_message': 'Thanks for subscribing!'})

templates/Profile/index.html
{% extends "base.html" %}
{% load staticfiles %}

<!-- Navbar -->

{% block navigation %}

  <li class="nav-item">
    <a class="nav-link js-scroll-trigger" href="#aboutme">About me</a>
  </li>
  <li class="nav-item">
    <a class="nav-link js-scroll-trigger" href="#blog">Blog</a>
  </li>
  <li class="nav-item">
    <a class="nav-link js-scroll-trigger" href="#projects">Projects</a>
  </li>
  <li class="nav-item">
    <a class="nav-link js-scroll-trigger" href="{% url "Profile:resume" %}">Resume</a>
  </li>
  <li class="nav-item">
    <a class="nav-link js-scroll-trigger" href="#signup">Contact</a>
  </li>

{% endblock %}

<!-- Heading Text  -->

{% block heading_text %}{{blurb}}{% endblock %}

{% block content %}

<!-- About Section -->

  <section id="aboutme" class="aboutme-section bg-light">
    <div class="container">
      <div class="jumbotron">
        <div class="row align-items-center no-gutters mb-4 mb-lg-5">
          <div class="col-xl-6 col-lg-5 pl-5">
            <div class="featured-text text-center text-lg-left">
              <p class="text-white-50 pl-5 pr-5 pb-0 about-me">
                {% if about_me %}
                  {{ about_me.description }}
                {% else %}
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                {% endif %}
              </p>
            </div>
          </div>
          <div class="col-xl-6 col-lg-7 pl-5">
            {% if about_me %}
              <img class="profile_pic" src="{{ about_me.profile_picture.url }}" alt="">
            {% else %}
              <img class="profile_pic" src="{% static "base/img/Cthulhu.png" %}" alt="">
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </section>

<!-- Blog Section -->

  <section id="blog" class="blog-section bg-light">
    <div class="container">
      <div class="row align-items-center no-gutters mb-4 mb-lg-5">
        <div class="col-xl-8 col-lg-7">
          <div class="card text-center">
            <div class="card-header">
              <h4 class="text-white">Featured</h4>
            </div>
            <div class="card-body">
              <h5 class="card-title">{{ recent_blogpost.title }}</h5>
              <p class="card-text">{{ recent_blogpost.preview }}</p>
              <a href="{% url "Blog:Blog_index" %}" class="btn btn-primary">Visit the Blog</a>
            </div>
            <div class="card-footer text-muted">
              {{ recent_blogpost.posted_at }}
            </div>
          </div>
        </div>
        <div class="col-xl-4 col-lg-5">
          <div class="featured-text text-center text-lg-left">
            <h4>The Blog of Cthoder</h4>
            <p class="text-black-50 mb-0">
              A place to enjoy cool Lovecraftian pictures and my code ramblings.
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>

<!-- Projects Section -->
  <section id="projects" class="projects-section bg-light">
    <div class="container">


      {% for project in projects %}

      <!-- Project picture left-aligned -->
        {% if forloop.counter0|divisibleby:2 %}
          <div class="row justify-content-center no-gutters mb-5 mb-lg-0">
            <div class="col-lg-6">
              <div class="imagewrap">
                <img class="img-fluid" src="{{ project.project_picture.url }}" alt="">
              </div>
              <div class="aligner">
                <div class="button-container">
                  <a class="enbBtn" href="{{ project.project_url }}"><strong>VIEW PROJECT</strong></a>
                </div>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="bg-black text-center h-100 project">
                <div class="d-flex h-100">
                  <div class="project-text w-100 my-auto text-center text-lg-left">
                    <h4 class="text-white">{{ project.title }}</h4>
                    <p class="mb-0 text-white-50">{{ project.summary }}</p>
                    <hr class="d-none d-lg-block mb-0 ml-0">
                  </div>
                </div>
              </div>
            </div>
          </div>

        {% else %}
          <!-- Project picture right-aligned -->
          <div class="row justify-content-center no-gutters">
            <div class="col-lg-6">
              <div class="imagewrap">
                <img class="img-fluid" src="{{ project.project_picture.url }}" alt="">
              </div>
              <div class="aligner">
                <div class="button-container">
                  <a class="enbBtn" href="{{ project.project_url }}"><strong>VIEW PROJECT</strong></a>
                </div>
              </div>
            </div>
            <div class="col-lg-6 order-lg-first">
              <div class="bg-black text-center h-100 project">
                <div class="d-flex h-100">
                  <div class="project-text w-100 my-auto text-center text-lg-left">
                    <h4 class="text-white">{{ project.title }}</h4>
                    <p class="mb-0 text-white-50">{{ project.summary }}</p>
                    <hr class="d-none d-lg-block mb-0 ml-0">
                  </div>
                </div>
              </div>
            </div>
          </div>

        {% endif %}
        {% endfor %}

    </div>
  </section>


<script src="{% static "base/js/Projects.js" %}" charset="utf-8"></script>

{% endblock %}