Blog/urls.py
from django.urls import path
from .views import (BlogIndexView, Login, LogOut, ReplyHandler, Registration,
                    UpdateDeleteComment, VotesHandler)

app_name = 'Blog'

urlpatterns = [
    path('',
        BlogIndexView.as_view(),
        name='Blog_index',
        ),
    path(
        'Comment/Delete/<int:comment_pk>/',
        UpdateDeleteComment,
        name='Delete_comment',
        ),
    path(
        'Comment/Update/<int:comment_pk>/',
        UpdateDeleteComment,
        name='Update_comment',
        ),
    path(
        'Login/',
        Login.as_view(),
        name='Login',
        ),
    path(
        'Login/<str:error>/',
        BlogIndexView.as_view(),
        name="Login_error",
        ),
    path(
        'Logout/',
        LogOut.as_view(),
        name='Logout',
        ),
    path(
        'Reply/<str:parent_comment_pk>/',
        ReplyHandler,
        name='Reply',
        ),
    path(
        'Registration/',
        Registration,
        name='Registration',
        ),
    path(
        'Registration/<str:error_type>/',
         BlogIndexView.as_view(),
         name='Registration_error',
        ),
    path(
        'Vote/<int:comment_pk>/<str:vote_type>/',
        VotesHandler,
        name='Vote',
        ),
]

CallofCthoder/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(
        'admin/',
        admin.site.urls,
        ),
    path(
        'blog/',
        include('Blog.urls'),
        ),
    path('',
        include('Profile.urls'),
        ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Profile/urls.py
from django.urls import path

from .views import IndexView, SubscriptionHandler, ResumeView

app_name = 'Profile'

urlpatterns = [
    path(
        '',
        IndexView.as_view(),
        name='index',
        ),
    path(
        'BNResume/',
        ResumeView,
        name='resume',
        ),
    path(
        'Subscription/',
        SubscriptionHandler,
        name='subscription',
        ),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
{% load staticfiles %}

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>The Call of Cthoder</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{% static "base/vendor/bootstrap/css/bootstrap.min.css" %}">

  <!-- Custom fonts for this template -->
  <link href="{% static "base/vendor/fontawesome-free/css/all.min.css" %}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Arvo" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href={% static "base/css/callofcthoder.css" %} rel="stylesheet">

</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">The Call of Cthoder</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          {% block navigation %}{% endblock %}
        </ul>
      </div>
    </div>
  </nav>

  <!-- Heading Section -->
  <section id="about" class="about-section text-center">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <h2 class="text-white mb-4">Benjamin Van Nguyen</h2>
          <p class="text-white-50">{% block heading_text %}{% endblock %}</p>
        </div>
      </div>
    </div>
  </section>

{% block content %}{% endblock %}

  <!-- Signup Section -->
  <section id="signup" class="signup-section">
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-lg-8 mx-auto text-center">

          <h2 class="text-white mb-5 subscription-message">Subscribe to be notified about new blog entries!</h2>

          <form class="form-inline d-flex subscribe-form" action="{% url "Profile:subscription" %}" method="post">
            {% csrf_token %}
            <input name='user_email' type="email" class="form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0" id="inputEmail" placeholder="Enter email address...">
            <button type="submit" class="btn btn-primary mx-auto subscribe-button">Subscribe</button>
          </form>


        </div>
      </div>
    </div>
  </section>

  <!-- Contact Section -->
  <section class="contact-section bg-black">
    <div class="container">

      <div class="row">

        <div class="col-md-4 mb-3 mb-md-0">
          <div class="card py-4 h-100">
            <div class="card-body text-center">
              <i class="fab fa-github-alt text-primary mb-2"></i>
              <h4 class="text-uppercase m-0">Github</h4>
              <hr class="my-4">
              <div class="small text-black-50"><a href="{{contact_info.github}}">{{contact_info.github}}</a></div>
            </div>
          </div>
        </div>

        <div class="col-md-4 mb-3 mb-md-0">
          <div class="card py-4 h-100">
            <div class="card-body text-center">
              <i class="fas fa-envelope text-primary mb-2"></i>
              <h4 class="text-uppercase m-0">Email</h4>
              <hr class="my-4">
              <div class="small text-black-50">
                <span class="personal-email">{{ contact_info.email }}</span>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-4 mb-3 mb-md-0">
          <div class="card py-4 h-100">
            <div class="card-body text-center">
              <i class="fab fa-linkedin-in text-primary mb-2"></i>
              <h4 class="text-uppercase m-0">LinkedIn</h4>
              <hr class="my-4">
              <div class="small text-black-50"><a href="{{ contact_info.linkedin }}">{{ contact_info.linkedin }}</a></div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </section>

  <!-- Footer -->
  <footer class="bg-black small text-center text-white-50">
    <div class="container">
      Copyright &copy; Benjamin Van Nguyen 2019
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static "base/vendor/jquery/jquery.min.js" %}"></script>
  <script src="{% static "base/vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static "base/vendor/jquery-easing/jquery.easing.min.js" %}"></script>
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/default.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/highlight.min.js"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static "base/js/callofcthoder.min.js" %}"></script>

  <!-- Jquery CDN-->
  <script
  src="https://code.jquery.com/jquery-3.4.0.js"
  integrity="sha256-DYZMCC8HTC+QDr5QNaIcfR7VSPtcISykd+6eSmBW5qo="
  crossorigin="anonymous"></script>

  <!-- Custom Jquery -->
  <script src="{% static "base/js/vote.js" %}" charset="utf-8"></script>
  <script src="{% static "base/js/comment.js" %}" charset="utf-8"></script>
  <script src="{% static "base/js/reply.js" %}" charset="utf-8"></script>
  <script src="{% static "base/js/reply_secondary.js" %}" charset="utf-8"></script>
  <script src="{% static "base/js/subscriptions.js" %}" charset="utf-8"></script>
  <script src="{% static "base/js/modal.js" %}" charset="utf-8"></script>
  <script src="{% static "base/js/delete_comment.js" %}" charset="utf-8"></script>
  <script src="{% static "base/js/edit_comment.js" %}" charset="utf-8"></script>
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/default.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/highlight.min.js"></script>
  <script>hljs.initHighlighting();</script>

</body>

</html>

templates/test.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>hmmmmm</h1>
  </body>
</html>